name: skater-elo-ratings

on:
  schedule:
    - cron:  '47 * * * *'

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install microprediction
            pip install pystan
            pip install --upgrade git+https://github.com/microprediction/timemachines.git
      - name: update elo ratings and test skaters
        run: |
          python update_skater_elo_ratings.py
    
      - name: Show git status
        run: | 
          git status
      - name: Add regression_test_results files
        run: |
          git config --local user.name  ${{ github.actor }}
          git config --local user.email "my@email.com"
          git add --all           
      - name: Show git status
        run: | 
          git status
          
      - name: Commit
        run: |  
          git commit -a -m "commiting test results"
          
      - name: git pull I
        run: | 
          git pull
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
      - name: test skaters II
        run: |
          python update_skater_elo_ratings.py
      
      - name: Commit II
        run: |  
          git commit -a -m "commiting test results"
          
      - name: git pull II
        run: | 
          git pull
          
      - name: Push changes II
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
          
      - name: test skaters III
        run: |
          python update_skater_elo_ratings.py
          
      - name: git pull III
        run: | 
          git pull
      
      - name: Commit III
        run: |  
          git commit -a -m "commiting test results"
          
      - name: Push changes III
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
      - name: test skaters IV
        run: |
          python update_skater_elo_ratings.py
          
      
      - name: Commit IV
        run: |  
          git commit -a -m "commiting test results"
          
      - name: git pull IV
        run: | 
          git pull
          
      - name: Push changes IV
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
